# Generated by Django 5.0 on 2025-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_product_brand_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
