# Generated by Django 5.2 on 2025-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_productenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.AlterModelOptions(
            name='productenquiry',
            options={'verbose_name': 'Product Enquiry', 'verbose_name_plural': 'Product Enquiries'},
        ),
    ]
