# Generated by Django 5.2 on 2025-06-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
    ]
