# Generated by Django 5.2 on 2025-06-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.FileField(null=True, upload_to='mobile_banners/'),
        ),
    ]
